### ISSUE TITLE
Consider releasing 2.0.0

### ISSUE THREAD

**Issue by budziq** [ia0/data-encoding#10]
Hi,

We've been using data_encoding 2.0.0-rc.2 for some time. Are there any roadblocks to release 2.0.0?

**Comment by ia0** [comment]
Hi Michał,

Thanks for your interest in this library.

The current reason why I'm not releasing yet is that I wanted to prove the algorithm first (I am currently using Why3 after trying FStar). However, this is way more challenging than what I initially thought.

So I'll just probably release 2.0.0-rc.2 as 2.0.0 this week-end and continue the proof after the release. I keep this issue open until the release.

**Comment by budziq** [comment]
> So I'll just probably release 2.0.0-rc.2 as 2.0.0 this week-end

 Thanks! I'm looking forward to it!

**Comment by ia0** [comment]
I released 2.0.0 today. I'm thus closing this issue. Thanks for having opened it.

**Comment by budziq** [comment]
Thanks!
