### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by kpcyrd** [ia0/data-encoding#26]
Hello!

I ran into this crate while packaging rust software for debian and there are some outdated dependencies, specifically:

- proc-macro-hack
- syn

The proc-macro-hack dependency can be bumped without any further changes, but the syn dependency bump needs some changes.

While we can technically upload outdated versions to debian we would like to avoid packaging old versions of crates since we'd have to maintain them along with the recent versions.

Releasing an update with the latest proc-macro-hack and syn would be greatly appreciated. Thanks!

**Comment by ia0** [comment]
Hi!

Thanks for your message. I'm going to look into this issue:
1. Update the dependencies.
2. Add a test for outdated dependencies.

I'll keep this bug to track both issues.

**Comment by ia0** [comment]
This issue should now be fixed. The data-encoding-macro-internal and data-encoding-macro have been published at 0.1.7. Thanks again for the report!

**Comment by kpcyrd** [comment]
That was fast, thanks! :)
