### ISSUE TITLE
Add decoding with padding stripped at least to base64url

### ISSUE THREAD

**Issue by golddranks** [ia0/data-encoding#3]
Hi, first of all, thanks for this tremendous crate!

It's quite a common operation to send fixed-length base64(url)-encoded hmacs, tokens etc. in HTTP cookies and urls. It also common to strip the padding characters away because they often cause problems (interfering with reserved characters in URLs and HTTP headers). Since the message is fixed-length, the padding isn't needed anyway.

It would be neat to add a helper method for decoding padding-stripped base64 for known-length messages. At the moment it's possible to manually add the paddings using the output of `encode_len` as a target length, but, this is problematic especially if one strives for copying things as little as possible – if you're passed an immutable slice, you just have to copy it to be able to add the paddings.

**Comment by golddranks** [comment]
Do you accept pull requests? I can try and implement such a helper function when I have time.

**Comment by ia0** [comment]
Hi,

Thanks a lot for your feedback. This is indeed something I have planned. I'll take a look tonight to give you more information. Do you have any time constraint about this feature?

**Comment by golddranks** [comment]
Do you mean that do I need the feature for my work quickly? Not actually, I'm fine with a hand-rolled padding-stripping code at the moment, just thought it would be a nice feature for the library to provide.

**Comment by ia0** [comment]
Yes, I meant if the feature is blocking your work. If you have a workaround, it will give me more time to integrate the feature instead of adding it as an extension.

This is indeed a nice feature for the library and it is planned to be done. I already worked on it a few months ago but don't remember the outcome. I'll have to take a look tonight.

**Comment by ia0** [comment]
I finally ended up implementing it as side functions in v1.2.0. My other changes to make it nicer are actually breaking changes. I'll have to work on them enough time before I make it a v2.

Thanks for making me look at this project again! :-)

**Comment by golddranks** [comment]
Thanks, seems to work well!

**Comment by ia0** [comment]
@golddranks By the way, in the v2.0.0-rc.1 release, using non-padded encodings is made simpler (through the `NoPad` type). You may want to migrate from v1 to v2. Simple instruction steps are provided in the [documentation].

[documentation]: http://ia0.github.io/data-encoding/v2.0.0-rc.1/data_encoding/#migration
