### ISSUE TITLE
Releasing new version of data_encoding_macro

### ISSUE THREAD

**Issue by vmx** [ia0/data-encoding#32]
Could you please release a new version of data_encoding_macro? I'm interested in a version that depends on syn >= 1.0.

**Comment by ia0** [comment]
Yes. I'm surprised I didn't do it already. I'll try to do it this weekend.

**Comment by ia0** [comment]
Done:
https://crates.io/crates/data-encoding-macro
https://crates.io/crates/data-encoding-macro-internal

**Comment by vmx** [comment]
Thank you so much!

**Comment by ia0** [comment]
No problem :-) Thank _you_ for reminding me of doing it.
