### ISSUE TITLE
Encoding into a String?

### ISSUE THREAD

**Issue by L-as** [ia0/data-encoding#34]
I am trying to figure out how I'd encode into a String, but it doesn't seem to be possible without using `unsafe`. Is this intentional? Is there something I'm overlooking? Thanks.

**Comment by ia0** [comment]
Hi, you should be able to use [this function](https://docs.rs/data-encoding/2.2.1/data_encoding/struct.Encoding.html#method.encode) depending on your use-case. Could you tell me a bit more if that function doesn't satisfy your need? Thanks!

**Comment by L-as** [comment]
Sorry for not being clear enough: I am wondering if there is a way to write into a &mut String without allocating an intermediary String. Thanks.

**Comment by ia0** [comment]
I see, indeed this is a missing feature. If I understand correctly, you are suggesting adding something like:

```rust
/// Appends the encoding of `input` to `output`
pub fn encode_mut_string(&self, input: &[u8], output: &mut String)
```

This looks like a useful function. I will need to think a bit about the naming and see if I don't merge it with `encode_mut` using a trait for the supported output types.

When would you need such function?

In the meantime, I guess you already use something similar to [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=701d66266ab1833f4465f0615aef12b1) as a workaround.

**Comment by L-as** [comment]
I am building a String which I then use elsewhere. I could make it a Vec<u8> instead, but that would mean I have to check that it's correct UTF-8 later, OR I could just use your workaround (which I am *not* using, so thanks!). Thanks for the help, it's a really nice crate.

**Comment by ia0** [comment]
No problem, thanks! I'll take a look at it when I get time.

Indeed, users should not have to use Vec instead of String for output of encoding functions. In particular, `data-encoding` provides the guarantee that output is ASCII, so the unsafe code should be hidden in the library so that users can use a safe API.

**Comment by ia0** [comment]
`data-encoding 2.3.0` has been released and provides an `encode_append` function as requested. If anything is wrong, please reopen the issue. Thanks for the initial feedback!
