### ISSUE TITLE
add lower case a-z for base16 or maybe base32

### ISSUE THREAD

**Issue by sbant** [ia0/data-encoding#5]
for example: I need to gen MD5 for the bytes of hex,
the rustc_serialize::hex generate hex as lower case a-z.

If data-encoding will add this?

**Comment by ia0** [comment]
Yes, data-encoding will add this in v2.0.0 which is currently in progress. However I have a few questions:
- Do you need decode to also support uppercase letters? In other words, is `38a9F1` a valid hex encoding? (v2.0.0 will support this optionally in a case-insensitive setting)
- Do you need this feature before May 2017? (I suspect v2.0.0 to be ready during April/May 2017. If you don't need a case-insensitive decode then I can add a hex_low module handling this in v1.3.0 tonight)

**Comment by sbant** [comment]
I feel mix lower and upper case is not needed(never saw in other implemention)
currently, I use rustc_serailize::hex withour problem, but wish can get rid of it.

**Comment by dbrgn** [comment]
> v2.0.0 will support this optionally in a case-insensitive setting

Yeah, looking forward to that!

**Comment by ia0** [comment]
@sbant You can now use the [`HEXLOWER`][1] constant of v2.0.0-rc.1. You would typically use it like `HEXLOWER.encode(input)` and `HEXLOWER.decode(input)`.

@dbrgn There is now a [`HEXLOWER_PERMISSIVE`][2] constant in v2.0.0-rc.1 that works as `HEXLOWER` but also accepts upper-case. Note that with v2.0.0-rc.1 you can easily define you own encoding and get the exact same performance as the predefined ones.

The v2.0.0-rc.1 will move to v2.0.0 in about one month depending on feedback.

[1]: http://ia0.github.io/data-encoding/v2.0.0-rc.1/data_encoding/constant.HEXLOWER.html
[2]: http://ia0.github.io/data-encoding/v2.0.0-rc.1/data_encoding/constant.HEXLOWER_PERMISSIVE.html

**Comment by lucab** [comment]
@ia0 is the v2 ETA still end of May?

**Comment by ia0** [comment]
@lucab No. I am working on an rc2 that unifies the NoPad and Padded types and allows to ignore characters during decoding. I don't know yet when I'll be done (prototype is done though). It will probably be out before end of June, but I am not sure I'll have enough time.

**Comment by lucab** [comment]
I see. No hurry, and thanks for the status update!

**Comment by ia0** [comment]
Quick update on this issue. I released v2.0.0-rc.2 which should be the last candidate before v2.0.0 is released (before end of year).

I'm closing the issue since it should be fully solved by v2.0.0-rc.2.

**Comment by dignifiedquire** [comment]
any chance you could add lower case base32 variants?
