### ISSUE TITLE
Missing a new line and decode error

### ISSUE THREAD

**Issue by QMHTMY** [ia0/data-encoding#50]
![屏幕截图_5](https://user-images.githubusercontent.com/20437653/145139795-3dec65d6-650a-40ed-bee3-a1bb9966d34a.png)

1.encoded string is on the same line with prompt (mi@mi-OptiPlex-7060:~ 🐄).
2.decoded result has an error followed (data-encoding: invalid length at xx).

**Comment by ia0** [comment]
Hi @QMHTMY ,

Thanks for your question!

I see the concern is only about newline regarding command line tools. So I'll first describe how they work:
- `echo` is a tool that prints its arguments, separated by spaces and followed by a newline. If you don't want the newline, you can use `echo -n`. For example `echo abc` outputs `abc\n` (i.e. `6162630a` in hexa).
- `data-encoding` is a tool that converts strings without extra pretty-printing information, such that it can be used in more complex tools. For example `echo -n abc | data-encoding -me -b64` outputs `YWJj` and not `YWJj\n`.
- Shells (like bash) have different ways to show whether a command output contains a newline or not. For example in bash, the prompt is on the same line.

To solve your problems:
1. If you want a newline after `data-encoding` output, you can use `echo "$(echo -n abc | data-encoding -me -b64)"`.
2. To avoid the decoding error, you can remove the invalid newline in the input by using `echo -n YWJj | data-encoding -md -b64` (or `echo "$(echo -n YWJj | data-encoding -md -b64)"` if you want a newline in the output)

Note that you can also ignore newlines when decoding. For example `echo YWJj | data-encoding -md -b64 -g$'\n'` (the actual syntax to pass a newline to `-g` depends on your shell).

Hope this helps

**Comment by QMHTMY** [comment]
Thank you very much!
