### ISSUE TITLE
Use doc_auto_cfg once stable

### ISSUE THREAD

**Issue by ia0** [ia0/data-encoding#73]
The documentation currently manually mentions which feature needs to be enabled to use a function. This could be automated with [`doc_auto_cfg`](https://github.com/rust-lang/rust/issues/43781).

**Comment by Serial-ATA** [comment]
In case you didn't know, you can actually make use of it right now since docs.rs is on nightly anyway.

Cargo.toml:

```rust
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```

lib.rs:

```rust
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
```
